<template>
    <div id="content">
        <vs-card class="cardx" style="margin-top: 10px; background-color: rgba(255,255,255,0.6)">
            <div slot="header">
                <h3>Statistics</h3>
            </div>
            <div>
                <span>Here you will find personal statistics generated by your usage.</span>
                <vs-divider></vs-divider>
                <p>Attended events: </p>
                <p>Planned events: </p>
                <p>Money spent: </p>
            </div>
        </vs-card>
    </div>
</template>

<script>
    export default {
        name: "StatisticsCard"
    }
</script>

<style scoped>

</style>
